/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.13.0+p3-g40b6564e
 *
 * Project: 'CLOCK_SOURCE.Debug+PY32F002Bx5' 
 * Target:  'Debug+PY32F002Bx5' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "py32f0xx.h"



#endif /* RTE_COMPONENTS_H */
